//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscleApplication.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercises()
        {

            this.id = Guid.NewGuid().ToString();
            this.createdAt = DateTimeOffset.Now;
            this.RoutineExercises = new HashSet<RoutineExercises>();
            this.Sets = new HashSet<Sets>();
        }
    
        public string id { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public string ExerciseName { get; set; }
        public string ExerciseType { get; set; }
        public string ExerciseType2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineExercises> RoutineExercises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sets> Sets { get; set; }
    }
}
