//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscleApplication.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineExercises
    {
        public string id { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public string exerciseId { get; set; }
        public string routineId { get; set; }
    
        public virtual Exercises Exercises { get; set; }
        public virtual Routines Routines { get; set; }
    }
}
