//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscleApplication.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineExercise
    {
        public RoutineExercise()
        {
            Id = Guid.NewGuid().ToString();

        }
        public string Id { get; set; }
        public string ExerciseId { get; set; }
        public string RoutineId { get; set; }
    
        public virtual Exercise Exercises { get; set; }
        public virtual Routine Routines { get; set; }
    }
}
