//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscleApplication.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Routine()
        {
            Id = Guid.NewGuid().ToString();
            CreatedAt = DateTime.Now;
            this.RoutineExercises = new HashSet<RoutineExercise>();
            this.Workouts = new HashSet<Workout>();
        }
    
        public string Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastUsed { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoutineExercise> RoutineExercises { get; set; }
        public virtual User Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workout> Workouts { get; set; }
    }
}
