//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscleApplication.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {

            this.id = Guid.NewGuid().ToString();
            this.createdAt = DateTimeOffset.Now;
            this.Routines = new HashSet<Routines>();
            this.UserWorkouts = new HashSet<UserWorkouts>();
        }
    
        public string id { get; set; }
        public System.DateTimeOffset createdAt { get; set; }
        public Nullable<bool> deleted { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> height { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Routines> Routines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWorkouts> UserWorkouts { get; set; }
    }
}
