//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscleApplication.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout()
        {
            Id = Guid.NewGuid().ToString();
            CreatedAt = DateTime.Now;
            this.Sets = new HashSet<Set>();
        }
    
        public string Id { get; set; }
        public string RoutineId { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> EndedAt { get; set; }
    
        public virtual Routine Routines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Set> Sets { get; set; }
        public virtual User Users { get; set; }
    }
}
